"""The review-ready package manifest.

Because the chosen workflow is "generate, then post manually", the final
deliverable is a folder a human can open and act on: the assembled video,
the thumbnail, and the metadata to paste into the upload form, all
described by a single ``manifest.json`` plus a human-readable
``POST_CHECKLIST.md``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_manifest(run_dir: Path, config: Any, results: dict[str, Any]) -> Path:
    script = results.get("script", {})
    assemble = results.get("assemble", {})
    thumb = results.get("thumbnail", {})

    manifest = {
        "topic": config.topic,
        "style": config.style,
        "tone": config.tone,
        "aspect_ratio": config.aspect_ratio,
        "target_seconds": config.target_seconds,
        "title": script.get("title"),
        "title_alternatives": script.get("title_alternatives", []),
        "description": script.get("description"),
        "tags": script.get("tags", []),
        "assets": {
            "video": assemble.get("video"),
            "thumbnail": thumb.get("image"),
            "voiceover": results.get("voiceover", {}).get("audio"),
            "scene_clips": results.get("animation", {}).get("clips", []),
        },
        "scores": {
            "title": script.get("title_score"),
            "thumbnail": thumb.get("score"),
        },
        "ready_for_manual_post": bool(assemble.get("video") and thumb.get("image")),
    }

    manifest_path = run_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    _write_checklist(run_dir, manifest)
    return manifest_path


def _write_checklist(run_dir: Path, m: dict[str, Any]) -> None:
    tags = ", ".join(m.get("tags") or [])
    lines = [
        f"# Post checklist — {m.get('title') or m['topic']}",
        "",
        "This package was generated by the AI animation pipeline and is ready",
        "for you to review and upload manually.",
        "",
        "## 1. Review the assets",
        f"- Video: `{m['assets'].get('video')}`",
        f"- Thumbnail: `{m['assets'].get('thumbnail')}`",
        f"- Voiceover: `{m['assets'].get('voiceover')}`",
        "",
        "## 2. Copy the metadata",
        f"**Title:** {m.get('title')}",
        "",
        f"**Description:**\n\n{m.get('description')}",
        "",
        f"**Tags:** {tags}",
        "",
        "## 3. Title alternatives (if you want to A/B)",
        *[f"- {t}" for t in (m.get("title_alternatives") or [])],
        "",
        "## 4. Upload",
        "- [ ] Assets look right",
        "- [ ] Title / description / tags pasted in",
        "- [ ] Thumbnail uploaded",
        "- [ ] Published",
    ]
    (run_dir / "POST_CHECKLIST.md").write_text("\n".join(lines), encoding="utf-8")
