"""A self-contained provider that fakes every stage.

It writes real (placeholder) files to disk so a full run produces a
complete, inspectable package without any network access or credentials.
Use it to develop and test the orchestrator; swap in a real provider for
actual generation.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


class MockProvider:
    name = "mock"

    def research(self, topic: str, config: Any) -> dict[str, Any]:
        return {
            "topic": topic,
            "keywords": [topic, f"{topic} explained", f"how {topic} works"],
            "comparable_videos": [
                {"title": f"The truth about {topic}", "views": 1_200_000},
                {"title": f"{topic} in 60 seconds", "views": 840_000},
            ],
            "hook": f"What if everything you knew about {topic} was wrong?",
        }

    def write_script(self, research: dict[str, Any], config: Any) -> dict[str, Any]:
        topic = research["topic"]
        scenes = [
            {
                "id": 1,
                "narration": research["hook"],
                "visual_prompt": f"Bold opening title card for '{topic}', {config.style} style",
            },
            {
                "id": 2,
                "narration": f"Here's the core idea behind {topic}, in plain terms.",
                "visual_prompt": f"Animated diagram explaining {topic}, {config.tone} mood",
            },
            {
                "id": 3,
                "narration": "And here's why it matters to you. Follow for more.",
                "visual_prompt": f"Closing call-to-action scene about {topic}",
            },
        ]
        return {
            "title": f"{topic}, Explained in {config.target_seconds} Seconds",
            "title_alternatives": [
                f"The {topic} Secret Nobody Tells You",
                f"{topic}: What You Need to Know",
            ],
            "title_score": 78,
            "description": (
                f"A fully AI-generated short on {topic}.\n\n"
                f"{research['hook']}\n\nGenerated by the AI animation pipeline."
            ),
            "tags": research["keywords"],
            "scenes": scenes,
        }

    def voiceover(self, script: dict[str, Any], config: Any, out_dir: Path) -> dict[str, Any]:
        audio = out_dir / "voiceover.txt"  # placeholder for a .wav/.mp3
        narration = "\n".join(s["narration"] for s in script["scenes"])
        audio.write_text(
            f"[MOCK AUDIO — voice={config.voice or 'default'}]\n{narration}\n",
            encoding="utf-8",
        )
        return {"audio": str(audio), "duration_seconds": config.target_seconds}

    def animate(self, script: dict[str, Any], config: Any, out_dir: Path) -> dict[str, Any]:
        clips = []
        for scene in script["scenes"]:
            clip = out_dir / f"scene_{scene['id']:02d}.txt"  # placeholder for .mp4
            clip.write_text(
                f"[MOCK CLIP {scene['id']} — {config.aspect_ratio}]\n"
                f"prompt: {scene['visual_prompt']}\n",
                encoding="utf-8",
            )
            clips.append(str(clip))
        return {"clips": clips}

    def thumbnail(self, script: dict[str, Any], config: Any, out_dir: Path) -> dict[str, Any]:
        image = out_dir / "thumbnail.txt"  # placeholder for .png
        image.write_text(
            f"[MOCK THUMBNAIL]\ntitle: {script['title']}\nstyle: {config.style}\n",
            encoding="utf-8",
        )
        return {"image": str(image), "score": 82}

    def assemble(
        self,
        animation: dict[str, Any],
        voiceover: dict[str, Any],
        config: Any,
        out_dir: Path,
    ) -> dict[str, Any]:
        video = out_dir / "final_video.txt"  # placeholder for .mp4
        video.write_text(
            "[MOCK FINAL VIDEO]\n"
            f"aspect_ratio: {config.aspect_ratio}\n"
            f"clips: {animation['clips']}\n"
            f"audio: {voiceover['audio']}\n",
            encoding="utf-8",
        )
        return {"video": str(video), "duration_seconds": voiceover.get("duration_seconds")}
